=pod

=encoding utf8

=head1 NAME

App::cpantested - see cpan-tested

=head1 VERSION

version 0.001

=head1 SYNOPSIS

    cpan-outdated | cpan-tested | cpanm -n

=head1 DESCRIPTION

Pre-filter the output from the L<cpan-outdated> utility, crossing it with the results from the L<CPAN Testers Reports|http://cpantesters.org/>.

=head1 SEE ALSO

=over 4

=item *

L<App::cpanoutdated>

=item *

L<App::cpanminus>

=item *

L<App::cpantimes>

=item *

L<CPAN Testers Reports|http://cpantesters.org/>

=back

=head1 AUTHOR

Stanislaw Pusep <stas@sysd.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Stanislaw Pusep.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

